### ISSUE TITLE
Error: Unable to get pinning CSRF Token

### ISSUE THREAD

**Issue by ThomasBullock** [kengoldfarb/pin-it-node#15]
I've created a little command line app to scrape an array of images from a site then pin them. I was able to create a new board and create a few pins. Now I'm consistently getting... 
```
Error: Unable to get pinning CSRF Token
    at Request._callback (/Users/kingston/Sites/Pinterest Scrapper/node_modules/pin-it-node/index.js:147:20)
    at Request.self.callback (/Users/kingston/Sites/Pinterest Scrapper/node_modules/pin-it-node/node_modules/request/request.js:121:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/kingston/Sites/Pinterest Scrapper/node_modules/pin-it-node/node_modules/request/request.js:985:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/kingston/Sites/Pinterest Scrapper/node_modules/pin-it-node/node_modules/request/request.js:936:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

It happened after I tried to iterate over the array but now happens no matter what I do.

**Comment by kengoldfarb** [comment]
@ThomasBullock thanks for the report.  I'll look into it!

**Comment by kengoldfarb** [comment]
@ThomasBullock I just ran the tests and everything is passing for me.  I was able to create a pin, etc.

My initial thought since you were seeing it consistently work and then not is that you may be running into some kind of rate limiting from Pinterest.  Did this start happening after pinning a lot of stuff in a short amount of time?

They have rate limits in place but don't publish the actual numbers so it may take some trial and error to find a good interval: https://help.pinterest.com/en/articles/limits-and-blocks

If you're still seeing this issue after waiting a while, please turn on debugging and let me know what you see logged out to the console before the error occurs:

```
var pinIt = new PinIt({
    username: 'MyUsername',
    userurl: 'MyUrl',
    password: 'MySuperSecretPassword',
    debug: true
});
```

**Comment by ThomasBullock** [comment]
@kengoldfarb Thanks for the quick reply.
Yeah that makes sense. Problem first arose when I tried to do a bunch of createPins in a loop with no delay. Pinterest didn't like that. I just tried again with a different account and was able to create a board but when trying the createPin loop (this time with a setTimeout of 5000) again it's 'blocked' me.  Here's debug output.
```
_getLoginPageCSRF
COOKIE 0: _auth=0; Domain=.pinterest.com; expires=Mon, 19-Feb-2018 07:41:44 GMT; httponly; Max-Age=31103999; Path=/; secure
COOKIE 1: csrftoken=AeS05AmL8zv8bjPqww8AClB8IGUSPNqI; expires=Fri, 23-Feb-2018 07:41:44 GMT; Max-Age=31449600; Path=/; secure
COOKIE 2: _pinterest_sess=TWc9PSZrR3dEOXByTVlOcXJRcGNKekh4U1hwY2M1Vk9wa0lvQkRTOGtwb1lJUkNFYTZrandFeXB5enhiM3UrWkpEdzRuNEtOTUZjWUFWZ2F2dWZrVkx0Qy82c1J3ZmhScXRkYVhQazZoTFJsbkhIQjBaMkZHMFhwelNrajFYT2hMdkxCRzc3T1k3bWhGOTNEMm1sYmR2K1Z3dkE9PSZibGw3a0JWR2lBSTkvTUw1MDhiV004TWxidGc9; Domain=.pinterest.com; expires=Mon, 19-Feb-2018 07:41:44 GMT; httponly; Max-Age=31103999; Path=/; secure
CSRF Token: AeS05AmL8zv8bjPqww8AClB8IGUSPNqI
SUCCESS: _getLoginPageCSRF
_doLogin
SUCCESS: _doLogin
_getNewCSRFForPinning
! ERROR: _getNewCSRFForPinning
null
400

Error: Unable to get pinning CSRF Token
    at Request._callback (/Users/MotiMac/Sites/Pinterest Scrapper/node_modules/pin-it-node/index.js:147:20)
    at Request.self.callback (/Users/MotiMac/Sites/Pinterest Scrapper/node_modules/pin-it-node/node_modules/request/request.js:121:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/MotiMac/Sites/Pinterest Scrapper/node_modules/pin-it-node/node_modules/request/request.js:985:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/MotiMac/Sites/Pinterest Scrapper/node_modules/pin-it-node/node_modules/request/request.js:936:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
Pinning!
_getLoginPageCSRF
COOKIE 0: _pinterest_pfob=disabled; Domain=.pinterest.com; expires=Mon, 24-Feb-2020 07:41:56 GMT; Max-Age=94607999; Path=/
CSRF Token: AeS05AmL8zv8bjPqww8AClB8IGUSPNqI
SUCCESS: _getLoginPageCSRF
_doLogin
! ERROR: _doLogin
null
Status code: 403
���X��\k��ƒ�+�Z`����Ѽ67�&��8�����n�٤�!�4��F���Tu�%R�8�� �  etc  etc 
```

**Comment by kengoldfarb** [comment]
@ThomasBullock going to close this.  Let me know if it wasn't due to rate limiting and I can reopen.

**Comment by NeXTs** [comment]
I got this error on second attempt to pin. What's the pinterest limits for posting? How often can I pin by API?

**Comment by kengoldfarb** [comment]
@NeXTs this library was originally created because Pinterest did not have a way to create a pin through their API.

It looks like they've added that ability so I'd recommend using their official library.  More info:
https://developers.pinterest.com/docs/sdks/js/
https://developers.pinterest.com/docs/api/pins/

**Comment by NeXTs** [comment]
Yeah, I've already figured it out 👍 
Thank you!
